NETPROSDK_PRJT := $(call my-dir)/..

NETPROSDK_INC :=
NETPROSDK_INC += $(NETPROSDK_PRJT)

NETPROSDK_MOD :=
NETPROSDK_MOD += $(NETPROSDK_PRJT)

NETPROSDK_SRC_FILES :=
NETPROSDK_SRC_FILES += $(wildcard $(foreach EVERY_NETPROSDK_MOD,$(NETPROSDK_MOD),$(EVERY_NETPROSDK_MOD)/*.c $(EVERY_NETPROSDK_MOD)/*.cpp $(EVERY_NETPROSDK_MOD)/*.cxx $(EVERY_NETPROSDK_MOD)/*.cc $(EVERY_NETPROSDK_MOD)/*.s))