LOCAL_PATH := $(call my-dir)

NETPROSDK_WORKSPACE := $(LOCAL_PATH)/../../NetSDK
include $(NETPROSDK_WORKSPACE)/android-build/NetProSDK.mk
include $(NETPROSDK_WORKSPACE)/common/android-build/common.mk
include $(NETPROSDK_WORKSPACE)/GOSCAM/android-build/GOSCAM.mk

include $(CLEAR_VARS)

LOCAL_MODULE := libNetSDK

LOCAL_CFLAGS := -D__STDC_CONSTANT_MACROS

LOCAL_CPPFLAGS += -fexceptions -lgcc_s -lc


LOCAL_CFLAGS     += $(APP_CFG_CFLAGS)
LOCAL_LDLIBS     := $(APP_CFG_LDLIBS)

LOCAL_C_INCLUDES :=
LOCAL_C_INCLUDES += $(GOSCAM_INC)
LOCAL_C_INCLUDES += $(COMMON_INC)
LOCAL_C_INCLUDES += $(NETPROSDK_INC)


LOCAL_SRC_FILES :=
LOCAL_SRC_FILES += $(APP_CFG_FILES)
LOCAL_SRC_FILES += $(GOSCAM_SRC_FILES)
LOCAL_SRC_FILES += $(COMMON_SRC_FILES)
LOCAL_SRC_FILES += $(NETPROSDK_SRC_FILES)


LOCAL_LDLIBS :=-L$(NDK_PLATFORMS_ROOT)/$(TARGET_PLATFORM)/arch-arm/usr/lib -llog -lz -ldl -lgcc


include $(BUILD_SHARED_LIBRARY)


#include $(BUILD_STATIC_LIBRARY)


